title: <p align="center"> Sakar Pathak </P>
logo: /assets/img/sakar.jpg
description: I'm a Data Science student at the University of Arizona.
show_downloads: true
google_analytics:
theme: jekyll-theme-minimal
